/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */



/*
 Основные серьёзные ошибки:
 Ошибки с которыми столкнулся:
 * неправильно были выставлены адреса стэка в main.h, решил через инфу из Expressions
   был usagefault
 * В systick из регистра R0 в функцию попадал ненужный адрес и был Memfault
 */



#include <stdint.h>
#include <stdio.h>

#include "main.h"
#include "led.h"

#define INTERRUPT_DISABLE() do{__asm volatile ("MOV R0, #0X1"); __asm volatile ("MSR PRIMASK, R0"); } while(0)

#define INTERRUPT_ENABLE() do{__asm volatile ("MOV R0, #0X0"); __asm volatile ("MSR PRIMASK, R0"); } while(0)




extern void initialise_monitor_handles(void);

void task1_handler(void);
void task2_handler(void);
void task3_handler(void);
void task4_handler(void);


void task_delay(uint32_t tick_count);

// Current task
uint8_t current_task = 1; // Task1 run
uint32_t g_tick_count = 0; // For task_delay


typedef struct
{
	uint32_t psp_value;
	uint32_t block_count;
	uint8_t  current_state;
	void (*task_handler)(void);
} TCB_t;

TCB_t user_tasks[MAX_TASKS];

int main(void)
{

	initialise_monitor_handles();

	setbuf(stdout, NULL);

    enable_faults();

    initialize_task_scheduler(SCHEDULER_START);

	printf("task scheduler\n");

    initialize_task_stack();

    initialize_led();

    initialize_systick(TICK_HZ);

    switch_to_psp();

    task1_handler();


	for(;;);
}

void idle_task(void)
{
	printf("Idle task\n");
	while(1);
}

void task1_handler(void)
{
	while(1)
	{
		printf("task1\n");
		led_on(LED_BLUE);
		task_delay(5000);
	}
}

void task2_handler(void)
{
	while(1)
	{
		printf("task2\n");
		led_off(LED_BLUE);
		task_delay(500);
	}
}

void task3_handler(void)
{
	while(1)
	{
		printf("task3\n");
		led_on(LED_BLUE);
		task_delay(2000);
		led_off(LED_BLUE);
		task_delay(2000);
		led_on(LED_BLUE);
		task_delay(2000);
	}
}

void task4_handler(void)
{
	while(1)
	{
		printf("task4\n");
		led_off(LED_BLUE);
		task_delay(500);
	}
}
void enable_faults(void)
{
	uint32_t* p_shcrs_addr = (uint32_t*) SHCRS_addr;
	*p_shcrs_addr |= (1 << 18); //Enabling usagefault
	*p_shcrs_addr |= (1 << 17); //Enabling busfault
	*p_shcrs_addr |= (1 << 16); //Enabling memfault
}

void initialize_systick(uint32_t tick_hz)
{
	uint32_t *p_syst_rvr_addr = (uint32_t*) SYST_RVR_addr;
	uint32_t *p_syst_csr_addr = (uint32_t*) SYST_CSR_addr;


	uint32_t count_value = (SYSTICK_TIM/tick_hz) - 1;


	*p_syst_rvr_addr &= ~(0x00FFFFFF);
	*p_syst_rvr_addr |= count_value;

	*p_syst_csr_addr |= (1 << 1);
	*p_syst_csr_addr |= (1 << 2);
	*p_syst_csr_addr |= (1 << 0);

}

__attribute__ ((naked)) void initialize_task_scheduler(uint32_t scheduler_start)
{
	__asm volatile ("MSR MSP, %0" : : "r" (scheduler_start) : );
	__asm volatile ("BX LR");
}



#define TASK_READY_STATE  0x00
#define TASK_BLOCKED_STATE  0xFF

void initialize_task_stack(void)
{

	user_tasks[0].current_state = TASK_READY_STATE;
	user_tasks[1].current_state = TASK_READY_STATE;
	user_tasks[2].current_state = TASK_READY_STATE;
	user_tasks[3].current_state = TASK_READY_STATE;
	user_tasks[4].current_state = TASK_READY_STATE;


	user_tasks[0].psp_value = IDLE_STACK_START;
	user_tasks[1].psp_value = T1_STACK_START;
	user_tasks[2].psp_value = T2_STACK_START;
	user_tasks[3].psp_value = T3_STACK_START;
	user_tasks[4].psp_value = T4_STACK_START;

	user_tasks[0].task_handler = idle_task;
	user_tasks[1].task_handler = task1_handler;
	user_tasks[2].task_handler = task2_handler;
	user_tasks[3].task_handler = task3_handler;
	user_tasks[4].task_handler = task4_handler;

	uint32_t *pPSP;
	for (uint8_t i = 0; i < MAX_TASKS; i++)
	{
		pPSP = (uint32_t*) user_tasks[i].psp_value;

		pPSP--;
		*pPSP = DUMMY_XPSR;

		pPSP--;
		*pPSP = (uint32_t) user_tasks[i].task_handler;

		pPSP--;
		*pPSP =  0xFFFFFFFD;

		for (uint8_t j = 0; j < 13; j++)
		{
			pPSP--;
			*pPSP = 0;
		}

		user_tasks[i].psp_value = (uint32_t) pPSP;

	}
}


uint32_t get_psp_value(void)
{
	return user_tasks[current_task].psp_value;
}

void save_psp_value(uint32_t current_psp_value)
{
	user_tasks[current_task].psp_value = current_psp_value;
}

void update_next_task(void)
{
	int state = TASK_BLOCKED_STATE;

	for(int i = 0; i < (MAX_TASKS); i++)
	{
		current_task++;
		current_task %= MAX_TASKS;
		state = user_tasks[current_task].current_state;
		if ((state == TASK_READY_STATE) && (current_task != 0))
			break;
	}
	if (state != TASK_READY_STATE)
		current_task = 0;
}

__attribute__ ((naked)) void switch_to_psp(void)
{
	// getting PSP
	__asm volatile ("PUSH {LR}"); // bcs LR is changing
	__asm volatile ("BL get_psp_value");
	__asm volatile ("MSR PSP, R0");
	__asm volatile ("POP {LR}");

	// Enabling PSP
	__asm volatile ("MOV R0, #0X02");
	__asm volatile ("MSR CONTROL, R0");
	__asm volatile ("BX LR");
}

void schedule(void)
{
	// PendSV
	uint32_t *p_icsr_addr = (uint32_t*) ICSR_ADDR;
	*p_icsr_addr |= (1 << 28);
}

void task_delay(uint32_t tick_count)
{

	// По-хорошему в RTOS нельзя так выключать прерывания, но это учебный пример
	INTERRUPT_DISABLE();

	if (current_task)
	{
		user_tasks[current_task].block_count = g_tick_count + tick_count;
		user_tasks[current_task].current_state = TASK_BLOCKED_STATE;
		schedule();
	}

	INTERRUPT_ENABLE();
}

void update_global_tick_count()
{
	g_tick_count++;
}

void unblock_tasks(void)
{
	for (uint8_t i = 1; i < MAX_TASKS; i++)
	{
		if (user_tasks[i].current_state != TASK_READY_STATE)
		{
			if (user_tasks[i].block_count == g_tick_count)
			{
				user_tasks[i].current_state = TASK_READY_STATE;
			}
		}
	}
}

// Handlers space:

__attribute__ ((naked)) void PendSV_Handler(void)
{
	// Getting PSP
	__asm volatile ("MRS R0, PSP");
	// store R4-R11
	__asm volatile ("STMDB R0!, {R4-R11}");
	// Store new PSP
	__asm volatile ("PUSH {LR}"); // Preventing error
	__asm volatile ("BL save_psp_value");

	// updating task
	__asm volatile ("BL update_next_task");
	// getting next PSP
	__asm volatile ("BL get_psp_value");
	// load R4-R11 of next task
	__asm volatile ("LDMIA R0!, {R4-R11}");
	// saving new PSP
	__asm volatile ("MSR PSP, R0");

	__asm volatile ("POP {LR}");

	__asm volatile ("BX LR");
}

void SysTick_Handler(void)
{
	uint32_t *p_icsr_addr = (uint32_t*) ICSR_ADDR;

	update_global_tick_count();
	unblock_tasks();

	*p_icsr_addr |= (1 << 28);
}

void HardFault_Handler(void)
{
	printf("HardFault");
	while(1);
}

void UsageFault_Handler(void)
{
	printf("UsageFault");
	while(1);
}

void BusFault_Handler(void)
{
	printf("BusFault");
	while(1);
}

void MemManage_Handler(void)
{
	printf("MemManage");
	while(1);
}
